export const personalInfo = {
  name: 'Arzaan Mogal',
  title: 'Predictive Analytics Graduate Candidate',
  subtitle: 'Data Science | Machine Learning | Business Intelligence | Analytics Consulting',
  location: 'Perth, Western Australia',
  email: 'arzaanmogal@gmail.com',
  phone: '+61 0431 786 090',
  linkedin: 'www.linkedin.com/in/arzaan-mogal31031999',
  github: 'https://github.com/Arzaan31',
  summary: `Master's candidate in Predictive Analytics at Curtin University with a background spanning business development, education consulting, analytics, and technology. My experience combines machine learning, business intelligence, predictive analytics, data visualization, stakeholder engagement, and problem solving. Passionate about transforming complex data into actionable insights that drive strategic decision making.`,
}

export const stats = [
  { value: '9+', label: 'Analytics & Technology Projects', icon: 'FolderOpen' },
  { value: '5+', label: 'Years Professional Experience', icon: 'Briefcase' },
  { value: '🏆', label: 'Smart India Hackathon Winner', icon: 'Trophy' },
  { value: "Master's", label: 'Candidate in Predictive Analytics', icon: 'GraduationCap' },
  { value: 'Guild', label: 'Student Councillor, Curtin University', icon: 'Users' },
  { value: '10+', label: 'Certifications & Professional Programs', icon: 'Award' },
]

export const education = [
  {
    degree: 'Master of Predictive Analytics',
    institution: 'Curtin University',
    location: 'Perth, Australia',
    period: 'July 2024 – December 2026',
    status: 'Current',
    areas: ['Machine Learning', 'Predictive Analytics', 'Business Intelligence', 'Data Mining', 'Data Visualization', 'Statistical Analysis', 'Data Engineering'],
  },
  {
    degree: 'Bachelor of Engineering (Information Technology)',
    institution: 'Marwadi Education Foundation Group of Institutions',
    location: 'India',
    period: '2016 – 2020',
    status: 'Completed',
    cgpa: '7.77',
    areas: ['Information Technology', 'Computer Science', 'Software Engineering'],
  },
]

export const skills = {
  programming: [
    { name: 'Python', level: 88 },
    { name: 'SQL', level: 85 },
    { name: 'R', level: 72 },
    { name: 'SQLite', level: 78 },
    { name: 'JavaScript', level: 65 },
    { name: 'HTML/CSS', level: 70 },
  ],
  dataScience: [
    { name: 'Machine Learning', level: 85 },
    { name: 'Predictive Analytics', level: 88 },
    { name: 'Statistical Analysis', level: 82 },
    { name: 'Feature Engineering', level: 80 },
    { name: 'Forecasting', level: 83 },
    { name: 'Data Mining', level: 78 },
  ],
  businessIntelligence: [
    { name: 'Tableau', level: 90 },
    { name: 'Power BI', level: 78 },
    { name: 'Dashboard Design', level: 88 },
    { name: 'Data Storytelling', level: 85 },
    { name: 'Data Visualization', level: 87 },
  ],
  databases: [
    { name: 'SQL / Relational DBs', level: 85 },
    { name: 'Database Design', level: 80 },
    { name: 'ER Modelling', level: 78 },
    { name: 'Normalization', level: 75 },
  ],
  professional: [
    { name: 'Communication', level: 92 },
    { name: 'Leadership', level: 88 },
    { name: 'Stakeholder Management', level: 85 },
    { name: 'Teaching & Mentoring', level: 90 },
    { name: 'Business Development', level: 82 },
  ],
}

export const experience = [
  {
    title: 'Tutor',
    company: 'Code Camp',
    location: 'Perth, Australia',
    period: 'September 2024 – Present',
    type: 'Technology Education',
    color: '#4a5eff',
    responsibilities: [
      'Teach coding concepts and computational thinking to students',
      'Deliver engaging, hands-on technology education sessions',
      'Support problem solving and logical reasoning development',
      'Mentor young learners through their first programming experiences',
    ],
    skills: ['Teaching', 'Communication', 'Leadership', 'Technical Mentoring'],
  },
  {
    title: 'Mathematics Tutor',
    company: 'Ezy Math Tutoring',
    location: 'Perth, Australia',
    period: 'August 2024 – Present',
    type: 'Education',
    color: '#2dd4bf',
    responsibilities: [
      'Deliver one-on-one tailored tutoring sessions',
      'Develop personalised learning plans for each student',
      'Coach quantitative reasoning and analytical thinking',
      'Track academic progress and adjust teaching approaches',
    ],
    skills: ['Mathematics', 'Analytical Thinking', 'Communication', 'Mentoring'],
  },
  {
    title: 'Team Member',
    company: 'Woolworths',
    location: 'Perth, Australia',
    period: 'December 2025 – Present',
    type: 'Operations',
    color: '#22c55e',
    responsibilities: [
      'Deliver consistent customer service standards',
      'Manage inventory and stock operations',
      'Support store operations and team workflows',
      'Collaborate effectively in a team environment',
    ],
    skills: ['Customer Service', 'Inventory Management', 'Operations', 'Team Collaboration'],
  },
  {
    title: 'Sales & Business Development',
    company: 'Red and White Multimedia Education',
    location: 'Rajkot, India',
    period: 'August 2023 – June 2024',
    type: 'Business Development',
    color: '#f59e0b',
    responsibilities: [
      'Conducted educational counselling and consultation sessions',
      'Developed strategic plans to increase student enrolments',
      'Facilitated workshops and educational events',
      'Built and maintained strong client and institutional relationships',
    ],
    skills: ['Sales', 'Business Development', 'Communication', 'Workshop Facilitation'],
  },
  {
    title: 'Business Development Associate',
    company: "BYJU'S",
    location: 'India',
    period: 'December 2021 – February 2023',
    type: 'Business Development',
    color: '#8b5cf6',
    responsibilities: [
      'Managed a portfolio of client relationships driving revenue growth',
      'Conducted market analysis to identify new business opportunities',
      'Developed and executed targeted sales strategies',
      'Collaborated cross-functionally with product and operations teams',
    ],
    skills: ['CRM', 'Market Analysis', 'Revenue Growth', 'Sales Strategy'],
  },
  {
    title: 'Computer Operator',
    company: 'Regail Computers',
    location: 'India',
    period: 'August 2020 – October 2021',
    type: 'Technology Operations',
    color: '#06b6d4',
    responsibilities: [
      'Managed day-to-day IT operations and infrastructure',
      'Resolved technical issues and performed troubleshooting',
      'Implemented process improvements for operational efficiency',
      'Managed hardware, software inventory and logistics',
    ],
    skills: ['IT Operations', 'Technical Troubleshooting', 'Process Improvement'],
  },
  {
    title: 'Intern',
    company: 'Soft Wisdom Technologies',
    location: 'India',
    period: 'Internship',
    type: 'Technology',
    color: '#ec4899',
    responsibilities: [
      'Supported web development and frontend implementation',
      'Provided IT support and system maintenance',
      'Assisted with data management and database tasks',
      'Contributed to software project delivery',
    ],
    skills: ['Web Development', 'IT Support', 'Data Management'],
  },
]

export const projects = [
  {
    id: 1,
    title: 'ESG & Sustainable Finance Analytics Dashboard',
    category: 'Business Intelligence',
    featured: true,
    tools: ['Tableau', 'Financial Analytics', 'Data Visualization'],
    description: 'Analyzed ESG performance trends among ASX and NZX listed companies from 2009–2024. Built a comprehensive Tableau Story covering market landscape, governance drivers, ESG correlations, and financial performance with what-if forecasting scenarios.',
    impact: 'Provided institutional-quality insights into relationships between sustainability practices, governance quality, and financial performance across 15 years of market data.',
    highlights: ['Market Landscape & ESG Trends', 'Governance Drivers & ESG Correlations', 'Financial Performance & What-if Forecasting'],
    color: '#4a5eff',
    icon: 'TrendingUp',
  },
  {
    id: 2,
    title: 'Australia Renewable Energy Analysis & Forecasting',
    category: 'Predictive Analytics',
    featured: true,
    tools: ['Python', 'Pandas', 'Forecasting', 'Data Visualization'],
    description: 'Analyzed renewable energy generation trends across Australia from 2005–2025 and developed forecasts for future growth trajectories across solar, wind, and hydro energy sources.',
    impact: 'Delivered data-driven forecasts supporting energy transition planning with trend analysis spanning 20 years of national energy data.',
    highlights: ['Time-series Forecasting', 'Trend Analysis', 'Multi-source Energy Data', 'Policy Implications'],
    color: '#2dd4bf',
    icon: 'Zap',
  },
  {
    id: 3,
    title: 'Data Mining Classification System',
    category: 'Machine Learning',
    featured: true,
    tools: ['Python', 'SQL', 'SQLite', 'Scikit-Learn', 'SMOTE'],
    description: 'Built and evaluated a multi-algorithm classification system with comprehensive data preprocessing, class imbalance handling using SMOTE, and rigorous model evaluation across five algorithms.',
    impact: 'Demonstrated systematic ML engineering from raw data through feature engineering to production-ready model comparison.',
    highlights: ['KNN • Naïve Bayes • Decision Tree', 'Random Forest • Gradient Boosting', 'SMOTE class imbalance handling', 'Feature engineering pipeline'],
    color: '#8b5cf6',
    icon: 'Brain',
  },
  {
    id: 4,
    title: 'Petrol Price Analytics Dashboard',
    category: 'Business Analytics',
    featured: false,
    tools: ['Microsoft Excel', 'Data Visualization'],
    description: 'Conducted comprehensive petrol price trend analysis using advanced Excel analytics, uncovering historical pricing patterns and building an interactive dashboard for stakeholder consumption.',
    impact: 'Translated complex commodity pricing data into accessible visual narratives for non-technical stakeholders.',
    highlights: ['Trend Analysis', 'Historical Pricing', 'Pattern Discovery', 'Dashboard Creation'],
    color: '#f59e0b',
    icon: 'BarChart2',
  },
  {
    id: 5,
    title: 'Data Management & Database Systems',
    category: 'Data Engineering',
    featured: false,
    tools: ['SQL', 'Database Design', 'ER Modelling'],
    description: 'Designed and implemented a normalized relational database system with full ER modelling, schema design, and optimized SQL query development for data integrity and performance.',
    impact: 'Delivered a production-ready database architecture demonstrating enterprise-grade data engineering practices.',
    highlights: ['ER Modelling', 'Schema Design', 'Normalization', 'SQL Query Optimization'],
    color: '#06b6d4',
    icon: 'Database',
  },
  {
    id: 6,
    title: 'Delivery Route Optimization System',
    category: 'Algorithms & Optimization',
    featured: false,
    tools: ['Python', 'Graph Algorithms'],
    description: 'Implemented a logistics route optimization system using graph data structures and pathfinding algorithms including BFS, DFS, and shortest path algorithms for delivery efficiency.',
    impact: 'Demonstrated applied algorithmic thinking for real-world logistics optimization problems.',
    highlights: ['Graph Implementation', 'BFS & DFS', 'Shortest Path Algorithms', 'Logistics Optimization'],
    color: '#22c55e',
    icon: 'Map',
  },
  {
    id: 7,
    title: 'Cybersecurity Risk Assessment',
    category: 'Cybersecurity',
    featured: false,
    tools: ['NIST SP 800-30', 'Risk Modelling'],
    description: 'Conducted a structured cybersecurity risk assessment following the NIST SP 800-30 framework, including threat identification, vulnerability analysis, risk modelling, and security recommendations.',
    impact: 'Produced a comprehensive risk report following industry-standard framework with actionable mitigation recommendations.',
    highlights: ['Threat Identification', 'Vulnerability Analysis', 'Risk Modelling', 'NIST Framework'],
    color: '#ef4444',
    icon: 'Shield',
  },
  {
    id: 8,
    title: 'Funding Analysis for Education Startup',
    category: 'Business Analytics',
    featured: false,
    tools: ['Business Analysis', 'Strategic Reporting'],
    description: 'Completed through the Study Australia Industry Experience Program (Practera). Conducted grant and funding opportunity analysis for an education startup, delivering strategic recommendations.',
    impact: 'Delivered actionable funding strategy to a real-world client through an industry consulting engagement.',
    highlights: ['Funding Research', 'Comparative Analysis', 'Strategic Recommendations', 'Industry Consulting'],
    color: '#ec4899',
    icon: 'DollarSign',
    badge: 'Industry Program',
  },
  {
    id: 9,
    title: 'Smart India Hackathon — National Winner',
    category: 'Hackathon',
    featured: true,
    tools: ['Data Analysis', 'Team Collaboration', 'Problem Solving'],
    description: 'National-level winning solution developed for the Ministry of Statistics and Programme Implementation challenge. Led data analysis, insight generation, and solution design in a competitive team environment.',
    impact: 'National-level recognition for delivering a high-impact data solution for a government statistics challenge.',
    highlights: ['National Winner', 'Government Challenge', 'Large-scale Data Analysis', 'Team Leadership'],
    color: '#f5c842',
    icon: 'Trophy',
    badge: '🏆 National Winner',
  },
]

export const leadership = [
  {
    role: 'Postgraduate Student Committee Councillor',
    organisation: 'Curtin Student Guild',
    period: 'September 2025 – September 2026',
    type: 'Student Government',
    color: '#4a5eff',
    responsibilities: ['Student representation at institutional level', 'Leadership and advocacy for postgraduate students', 'Stakeholder engagement with university administration', 'Policy input and student welfare initiatives'],
  },
  {
    role: 'International Student Committee Member',
    organisation: 'Curtin Student Guild',
    period: 'July 2024 – Present',
    type: 'Community',
    color: '#2dd4bf',
    responsibilities: ['Student engagement and community building', 'Support for international student transitions', 'Event participation and coordination', 'Cross-cultural community development'],
  },
  {
    role: 'Student Volunteer',
    organisation: 'TEDx Marwadi University',
    period: '2019',
    type: 'Event & Community',
    color: '#ef4444',
    responsibilities: ['Event coordination and logistics', 'Speaker and attendee support', 'Community engagement', 'Organizational management'],
  },
  {
    role: 'Member',
    organisation: 'National Service Scheme',
    period: '2016 – 2019',
    type: 'National Service',
    color: '#f59e0b',
    responsibilities: ['Community service initiatives', 'Social development programs', 'Leadership through service', 'National youth engagement'],
  },
]

export const certifications = [
  {
    name: 'Deloitte Australia Data Analytics Job Simulation',
    issuer: 'Deloitte via Forage',
    category: 'Industry Simulation',
    color: '#4a5eff',
    featured: true,
  },
  {
    name: 'Study Australia Industry Experience Program',
    issuer: 'Practera / Study Australia / ATIC',
    category: 'Industry Experience',
    color: '#2dd4bf',
    featured: true,
  },
  {
    name: 'CCNA Cybersecurity Operations',
    issuer: 'Cisco',
    category: 'Cybersecurity',
    color: '#06b6d4',
  },
  {
    name: 'Cisco Cybersecurity Essentials',
    issuer: 'Cisco',
    category: 'Cybersecurity',
    color: '#06b6d4',
  },
  {
    name: 'Cybersecurity Essentials Learn-A-Thon Badge',
    issuer: 'Cisco',
    category: 'Cybersecurity',
    color: '#06b6d4',
  },
  {
    name: 'Data Science Foundations',
    issuer: 'Professional Development',
    category: 'Data Science',
    color: '#8b5cf6',
  },
  {
    name: 'Google Ads Search Certification',
    issuer: 'Google',
    category: 'Digital Marketing',
    color: '#22c55e',
  },
  {
    name: 'Microsoft Virtual Academy — C# Fundamentals',
    issuer: 'Microsoft',
    category: 'Programming',
    color: '#0078d4',
  },
  {
    name: 'Advanced Android Development',
    issuer: 'Android Development Certification',
    category: 'Mobile Development',
    color: '#a4c639',
  },
]

export const blogPosts = [
  {
    slug: 'esg-analytics-tableau',
    title: 'Building an ESG Analytics Dashboard in Tableau: Lessons from ASX & NZX Data',
    category: 'Business Intelligence',
    date: 'March 2025',
    readTime: '8 min read',
    excerpt: 'How I designed a three-part Tableau Story analyzing 15 years of ESG performance data — from data preparation through to what-if forecasting for sustainable finance decisions.',
    tags: ['Tableau', 'ESG', 'Financial Analytics', 'Data Visualization'],
    color: '#4a5eff',
  },
  {
    slug: 'renewable-energy-forecasting',
    title: 'Forecasting Australia\'s Renewable Energy Future with Python',
    category: 'Predictive Analytics',
    date: 'February 2025',
    readTime: '6 min read',
    excerpt: 'A deep dive into forecasting renewable energy generation across Australia using time-series methods, covering data cleaning, trend decomposition, and model evaluation.',
    tags: ['Python', 'Forecasting', 'Energy Analytics', 'Pandas'],
    color: '#2dd4bf',
  },
  {
    slug: 'understanding-smote',
    title: 'Understanding SMOTE: Tackling Class Imbalance in Classification Problems',
    category: 'Machine Learning',
    date: 'January 2025',
    readTime: '7 min read',
    excerpt: 'Class imbalance can silently destroy your model\'s real-world performance. This post explains SMOTE, why it works, and how I applied it in a multi-algorithm classification project.',
    tags: ['SMOTE', 'Machine Learning', 'Scikit-Learn', 'Classification'],
    color: '#8b5cf6',
  },
  {
    slug: 'smart-india-hackathon',
    title: 'Winning Smart India Hackathon: What I Learned About Data Under Pressure',
    category: 'Experience',
    date: 'December 2024',
    readTime: '5 min read',
    excerpt: 'A behind-the-scenes reflection on winning India\'s largest national hackathon — the team dynamics, the data challenges, and the problem-solving mindset that made the difference.',
    tags: ['Hackathon', 'Data Analysis', 'Team Collaboration', 'Problem Solving'],
    color: '#f5c842',
  },
  {
    slug: 'effective-bi-dashboards',
    title: 'What Makes a Business Intelligence Dashboard Actually Effective',
    category: 'Business Intelligence',
    date: 'November 2024',
    readTime: '9 min read',
    excerpt: 'Beyond aesthetics — the principles I\'ve learned about building dashboards that drive decisions. Dashboard design, stakeholder needs, and the difference between data display and data insight.',
    tags: ['Dashboard Design', 'Power BI', 'Tableau', 'Data Storytelling'],
    color: '#06b6d4',
  },
  {
    slug: 'data-science-sustainable-finance',
    title: 'The Role of Data Science in Sustainable Finance',
    category: 'Analytics',
    date: 'October 2024',
    readTime: '7 min read',
    excerpt: 'ESG data is noisy, inconsistent, and growing fast. Exploring how predictive analytics and machine learning are reshaping how investors evaluate sustainability performance.',
    tags: ['ESG', 'Sustainable Finance', 'Data Science', 'Analytics'],
    color: '#22c55e',
  },
]
